### ISSUE TITLE
Get rid of TagCodes/DrawingOutput, instead use NFX Graphics directly 

### ISSUE THREAD

**Issue by itadapter** [agnicore/nfx#17]
This deals with Media/QR code rendering.

Old code used DrawingOutput as an abstraction layer.
This design is no longer needed since NFX5 provides .Graphics which IS already an abstraction layer

**Comment by itadapter** [comment]
Due 1/15/2018  Stabilization

**Comment by sergey-msu** [comment]
Done (code + unit tests)
