### ISSUE TITLE
Provide MySQL CRUD/connector functionality

### ISSUE THREAD

**Issue by agnibos** [agnicore/nfx#2]
Provide MySQL native support functionality

**Comment by agnibos** [comment]
see
  https://github.com/mysql-net/MySqlConnector (problem: uses ValueTask, System.Buffers etc as 3rd party nugets)

**Comment by itadapter** [comment]
started

**Comment by itadapter** [comment]
@vlapchenko Please cover the CRUD with MORE integration tests
especially do multi-threaded integration tests

**Comment by agnibos** [comment]
More testing is needed, but technically done

**Comment by itadapter** [comment]
Due 1/15/2018  Stabilization    @vlapchenko

**Comment by agnibos** [comment]
DONE
