### ISSUE TITLE
How does one run unit tests with "Aver"?

### ISSUE THREAD

**Issue by binfomater** [agnicore/nfx#41]
Never heard of "Aver" before. How do I run this?

**Comment by itadapter** [comment]
Aver is an assertion library which is <300 LOC, a part of NFX.
You use `Aver` just like you would use `Assert`.
In NFX, unit tests are not a "special kind" of software, to the contrary - it is a part of scriptable concept provided by `NFX.Scripting` namespace. 

Long story short:

Use `trun` unit test console tool. Go to `/out/run-netf` and run cli: `./trun NFX.UTest.dll -?` this will dump help with use-cases.
