### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by ShalokShalom** [agnicore/nfx#46]
Hi there :)

How is your F# support?

**Comment by ShalokShalom** [comment]
I found the documentation. It seems like you support only C#.
F# is in consideration?

**Comment by itadapter** [comment]
Nothing F#-special. Regular CIL code. What specifically are you interested in?

**Comment by ShalokShalom** [comment]
Well, syntax? How to use your library?

**Comment by agnibos** [comment]
There are plenty of resources:
http://nfxlib.com
https://github.com/aumcode/nfx-demos

**Comment by ShalokShalom** [comment]
Your API documentation shows only C#

**Comment by ShalokShalom** [comment]
So, you mean I am supposed to use C#?

**Comment by agnibos** [comment]
Not sure I understand your question. You can use ANY language that runs in Common Language Runtime

**Comment by ShalokShalom** [comment]
Your API documentation and all the links above show and use C#

How is the syntax in F#?

**Comment by agnibos** [comment]
Standard F# syntax. We do not use F# and do not have examples in F# or VB. You are welcome to contribute

**Comment by ShalokShalom** [comment]
Great, thanks ^-^
